name: CI Pipeline

on:
  push:
    branches:
      - feature
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'  # Caches dependencies to speed up installs

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pytest flake8  # Install linter & test runner

      - name: Run Linter (flake8)
        run: |
          flake8 . --max-line-length=88 --exit-zero
        continue-on-error: false  

      - name: Run Tests
        run: |
          pytest --exitfirst --disable-warnings  # Stop on first failure, hide warnings
